# Generated by Django 5.0.2 on 2024-02-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_profile_delete_profile_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='Present_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile pic'),
        ),
        migrations.DeleteModel(
            name='user_profile',
        ),
    ]
